# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppDevClean < Formula
  desc "Cross-platform dev-cache cleaner (RN/Expo/Flutter/native)"
  homepage "https://github.com/latif-essam/app-dev-clean"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/latif-essam/app-dev-clean/releases/download/v0.1.0/app-dev-clean_darwin_amd64.tar.gz"
      sha256 "15fffe9a9dc7b1f6fbbb3b1e93cc64dd7f161a9e121736ce25c9d3fead03a916"

      define_method(:install) do
        bin.install "app-dev-clean"
        bin.install_symlink "app-dev-clean" => "adc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/latif-essam/app-dev-clean/releases/download/v0.1.0/app-dev-clean_darwin_arm64.tar.gz"
      sha256 "b4cf7a3d6ea49dcea9cc1bfcd78df833d5a0ef4aa4bbee23bc72fff178d898f0"

      define_method(:install) do
        bin.install "app-dev-clean"
        bin.install_symlink "app-dev-clean" => "adc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/latif-essam/app-dev-clean/releases/download/v0.1.0/app-dev-clean_linux_amd64.tar.gz"
      sha256 "be95c9d05480db60bb3e464857325008e542f68ea57582c5f7289ec53cdc45c7"
      define_method(:install) do
        bin.install "app-dev-clean"
        bin.install_symlink "app-dev-clean" => "adc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/latif-essam/app-dev-clean/releases/download/v0.1.0/app-dev-clean_linux_arm64.tar.gz"
      sha256 "1955465eecffa4ef3cae7c78ef62244f996fd675f56b871f66e69e9fb724b27a"
      define_method(:install) do
        bin.install "app-dev-clean"
        bin.install_symlink "app-dev-clean" => "adc"
      end
    end
  end
end
